#!/bin/sh

# Executed by piaware to try to halt the machine.

echo "$0: trying to halt the machine" >&2

if sudo -n -l /sbin/halt >/dev/null; then
  sudo -n /sbin/halt
else
  echo "$0: no permission to attempt a halt" >&2
  exit 1
fi
