#!/bin/sh

# Executed by piaware to try to start dump1090.

echo "$0: trying to start dump1090" >&2

for choice in dump1090-mutability dump1090-flightaware dump1090-mr
do
  if [ -x /etc/init.d/$choice ]; then
    if sudo -n -l /etc/init.d/$choice start >/dev/null 2>&1; then
      echo "trying /etc/init.d/$choice.." >&2
      if sudo -n /etc/init.d/$choice start; then
        echo "started ok."
        exit 0
      fi
      echo "didn't start correctly."
    fi
  fi
done

echo "No suitable init.d script found, giving up" >&2
exit 1
